"""
This type stub file was generated by pyright.
"""

from .objects import Object
from .nodes import Node

class Comment(Node):
    def __init__(self, type, value, range=..., loc=...) -> None:
        ...
    


class Entry(Object):
    def __init__(self, comment, start) -> None:
        ...
    


class NodeInfo(Object):
    def __init__(self, node, start) -> None:
        ...
    


class CommentHandler:
    def __init__(self) -> None:
        ...
    
    def insertInnerComments(self, node, metadata): # -> None:
        ...
    
    def findTrailingComments(self, metadata): # -> list[Unknown]:
        ...
    
    def findLeadingComments(self, metadata): # -> list[Unknown]:
        ...
    
    def visitNode(self, node, metadata): # -> None:
        ...
    
    def visitComment(self, node, metadata): # -> None:
        ...
    
    def visit(self, node, metadata): # -> None:
        ...
    


