"""
This type stub file was generated by pyright.
"""

class Error(Exception):
    def __init__(self, message, name=..., index=..., lineNumber=..., column=..., description=...) -> None:
        ...
    
    def toString(self): # -> str:
        ...
    
    def toDict(self): # -> dict[Unknown, Any]:
        ...
    


class ErrorHandler:
    def __init__(self) -> None:
        ...
    
    def recordError(self, error): # -> None:
        ...
    
    def tolerate(self, error): # -> None:
        ...
    
    def createError(self, index, line, col, description): # -> Error:
        ...
    
    def throwError(self, index, line, col, description):
        ...
    
    def tolerateError(self, index, line, col, description): # -> None:
        ...
    


