"""
This type stub file was generated by pyright.
"""

__all__ = [
    "Syntax",
    "JSXSyntax",
    "Error",
    "NodeVisitor",
    "nodes",
    "jsx_nodes",
    "parse",
    "parseModule",
    "parseScript",
    "tokenize",
    "toDict",
]
from typing import Any, Callable, Optional, Union

from esprima.nodes import Module, Node, Script

def parse(code, options=..., delegate=..., **kwargs): ...
def parseModule(code, options=..., delegate=..., **kwargs): ...
def parseScript(
    code: str,
    options: Optional[dict[str, Any]] = ...,
    delegate: Callable[[Node, Any], Node] = ...,
    tolerant: bool = ...,
    jsx: bool = ...,
    **kwargs: dict[str, Any],
) -> Union[Module, Script]: ...
def tokenize(code, options=..., delegate=..., **kwargs): ...
