"""
This type stub file was generated by pyright.
"""

from .nodes import Node

class JSXClosingElement(Node):
    def __init__(self, name) -> None: ...

class JSXElement(Node):
    def __init__(self, openingElement, children, closingElement) -> None: ...

class JSXEmptyExpression(Node):
    def __init__(self) -> None: ...

class JSXExpressionContainer(Node):
    def __init__(self, expression) -> None: ...

class JSXIdentifier(Node):
    def __init__(self, name) -> None: ...

class JSXMemberExpression(Node):
    def __init__(self, object, property) -> None: ...

class JSXAttribute(Node):
    def __init__(self, name, value) -> None: ...

class JSXNamespacedName(Node):
    def __init__(self, namespace, name) -> None: ...

class JSXOpeningElement(Node):
    def __init__(self, name, selfClosing, attributes) -> None: ...

class JSXSpreadAttribute(Node):
    def __init__(self, argument) -> None: ...

class JSXText(Node):
    def __init__(self, value, raw) -> None: ...
