"""
This type stub file was generated by pyright.
"""

from typing import Any


def toDict(value):
    ...

class Array(list):
    ...


class Object:
    def toDict(self) -> dict[str, Any]:
        ...
    
    def __repr__(self):
        ...
    
    def __getattr__(self, name): # -> None:
        ...
    


