"""
This type stub file was generated by pyright.
"""

from .objects import Object

class BufferEntry(Object):
    def __init__(self, type, value, regex=..., range=..., loc=...) -> None:
        ...
    


class Reader:
    def __init__(self) -> None:
        ...
    
    def beforeFunctionExpression(self, t): # -> bool:
        ...
    
    def isRegexStart(self): # -> bool:
        ...
    
    def append(self, token): # -> None:
        ...
    


class Config(Object):
    def __init__(self, tolerant=..., comment=..., range=..., loc=..., **options) -> None:
        ...
    


class Tokenizer:
    def __init__(self, code, options) -> None:
        ...
    
    def errors(self): # -> list[Unknown]:
        ...
    
    def getNextToken(self): # -> None:
        ...
    


